apiVersion: v1
kind: Service
metadata:
  name: testserver-svc
  labels:
    app: testserver-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: testserver-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testserver-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver-deployment
    spec:
      containers:
      - name: testserver-deployment-pod
        image: vikrantatxoriant/testserver:2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  labels:
    app: mongoservice
spec:
  ports:
  - port: 27017
  selector:
    app: mongo-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      containers:
      - name: mongo-deployment-pod
        image: mongo
        ports:
        - containerPort: 27017